services:
  producer:
    build:
      context: .
      dockerfile: hon-producer/Dockerfile
    restart: always
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      RMQ_USERNAME: ${RMQ_USERNAME}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      RMQ_HOST: ${RMQ_HOST}
      RMQ_PORT: ${RMQ_PORT}
    env_file:
      - .env
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    env_file:
      - .env
    networks:
      - hon_network
  db:
    image: mysql:8.4
    container_name: db_mysql
    restart: always
    ports:
      - "${MYSQL_FORWARDED_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hon_network
    env_file:
      - .env

volumes:
  rabbitmq_data:
  db_data:
networks:
  hon_network:
    driver: bridge